import { BMRData } from './types';

export const mapDbToBMRData = (item: any): BMRData => ({
    id: item.id,
    productName: item.product_name,
    productCode: item.product_code,
    brandName: item.brand_name,
    productSize: item.product_size,
    batchNo: item.batch_no,
    batchSize: item.batch_size,
    mfgDate: item.mfg_date,
    expDate: item.exp_date,
    typeOfPacking: item.type_of_packing,
    dateOfCommencement: item.date_of_commencement,
    dateOfCompletion: item.date_of_completion,
    rawMaterials: item.raw_materials || [],
    packingMaterials: item.packing_materials || [],
    kitContents: item.kit_contents || [],
    bmrType: item.bmr_type || 'standard',
    productType: item.product_type,
    rawMaterialForSpecification: item.raw_material_for_specification,
    processSteps: item.process_steps || {},
    finalPacking: item.final_packing || {},
    sterilization: item.sterilization || {},
    labeling: item.labeling || {},
    declarations: item.declarations || {},
    status: item.status || 'draft',
    documentNo: item.document_no || '',
    revisionNo: item.revision_no || '',
    issueNo: item.issue_no || '',
});

export const mapBMRDataToDb = (data: BMRData, userId?: string) => ({
    product_name: data.productName,
    product_code: data.productCode,
    brand_name: data.brandName,
    product_size: data.productSize,
    batch_no: data.batchNo,
    batch_size: data.batchSize,
    mfg_date: data.mfgDate,
    exp_date: data.expDate,
    type_of_packing: data.typeOfPacking,
    date_of_commencement: data.dateOfCommencement,
    date_of_completion: data.dateOfCompletion,
    raw_materials: data.rawMaterials,
    packing_materials: data.packingMaterials,
    kit_contents: data.kitContents || [],
    process_steps: data.processSteps,
    sterilization: data.sterilization,
    labeling: data.labeling,
    final_packing: data.finalPacking,
    declarations: data.declarations,
    status: data.status,
    bmr_type: data.bmrType || 'standard',
    product_type: data.productType,
    raw_material_for_specification: data.rawMaterialForSpecification,
    generated_by: userId,
    updated_at: new Date().toISOString(),
});

export const mapDbToIncomingReport = (item: any) => ({
    ...item,
    invoiceDate: item.invoice_date,
    mfgDate: item.mfg_date,
    expDate: item.exp_date,
    sampleDate: item.sample_date,
    releaseDate: item.release_date,
    performanceLevel: item.performance_level,
    productName: item.product_name,
    reportNo: item.report_no,
    batchNo: item.batch_no,
    supplierId: item.supplier_name,
    batchSize: item.batch_size,
    invoiceNo: item.invoice_no,
    sampleQty: item.sample_qty,
    fabricComposition: item.fabric_composition,
    parametersResults: item.parameters_results,
    biocompatibilityResult: item.biocompatibility_result,
    visualResults: item.visual_results,
    testedBy: item.tested_by,
    reviewedBy: item.reviewed_by,
    generatedBy: item.generated_by,
});

export const mapIncomingReportToDb = (data: any, userId?: string) => ({
    product_name: data.productName,
    report_no: data.reportNo,
    performance_level: data.performanceLevel,
    batch_no: data.batchNo,
    supplier_name: data.supplierId,
    batch_size: data.batchSize,
    invoice_no: data.invoiceNo,
    invoice_date: data.invoiceDate,
    mfg_date: data.mfgDate,
    exp_date: data.expDate,
    sample_qty: data.sampleQty,
    sample_date: data.sampleDate,
    release_date: data.releaseDate,
    fabric_composition: data.fabricComposition,
    parameters_results: data.parametersResults,
    biocompatibility_result: data.biocompatibilityResult,
    visual_results: data.visualResults,
    result: data.result,
    tested_by: data.testedBy,
    reviewed_by: data.reviewedBy,
    generated_by: userId,
});
