-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bmr (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  product_name text NOT NULL,
  product_code text NOT NULL,
  brand_name text,
  product_size text,
  batch_no text NOT NULL UNIQUE,
  batch_size text,
  mfg_date date,
  exp_date date,
  type_of_packing text,
  date_of_commencement date,
  date_of_completion date,
  raw_materials jsonb DEFAULT '[]'::jsonb,
  packing_materials jsonb DEFAULT '[]'::jsonb,
  process_steps jsonb DEFAULT '{}'::jsonb,
  sterilization jsonb DEFAULT '{}'::jsonb,
  labeling jsonb DEFAULT '{}'::jsonb,
  final_packing jsonb DEFAULT '{}'::jsonb,
  declarations jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'draft'::text,
  bmr_type text DEFAULT 'standard'::text,
  kit_contents jsonb DEFAULT '[]'::jsonb,
  raw_material_for_specification bigint,
  product_type text,
  is_coa_generated boolean DEFAULT false,
  generated_by uuid,
  CONSTRAINT bmr_pkey PRIMARY KEY (id),
  CONSTRAINT bmr_raw_material_for_specification_fkey FOREIGN KEY (raw_material_for_specification) REFERENCES public.rm_test_reports(id),
  CONSTRAINT bmr_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.coa (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  bmr_id bigint,
  coa_no text,
  cover_type text,
  date_of_sample timestamp with time zone,
  completion_date timestamp with time zone,
  description text,
  rm_id bigint,
  rm_details json,
  physical_properties json,
  sterility text,
  result text,
  generated_by uuid,
  updated_at timestamp with time zone,
  CONSTRAINT coa_pkey PRIMARY KEY (id),
  CONSTRAINT coa_bmr_id_fkey FOREIGN KEY (bmr_id) REFERENCES public.bmr(id),
  CONSTRAINT coa_rm_id_fkey FOREIGN KEY (rm_id) REFERENCES public.rm_test_reports(id),
  CONSTRAINT coa_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.fabrics (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  supplier_id bigint,
  width text,
  CONSTRAINT fabrics_pkey PRIMARY KEY (id),
  CONSTRAINT fabrics_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.rm_test_reports (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  product_name text NOT NULL,
  report_no text NOT NULL UNIQUE,
  performance_level text NOT NULL,
  batch_no text NOT NULL UNIQUE,
  supplier_name bigint NOT NULL,
  batch_size text NOT NULL,
  invoice_no text NOT NULL,
  invoice_date timestamp with time zone NOT NULL,
  mfg_date timestamp with time zone,
  exp_date timestamp with time zone,
  sample_qty text NOT NULL,
  sample_date timestamp with time zone NOT NULL,
  release_date timestamp with time zone NOT NULL,
  fabric_composition text NOT NULL,
  parameters_results json NOT NULL,
  biocompatibility_result json NOT NULL,
  visual_results json NOT NULL,
  result text NOT NULL,
  tested_by text NOT NULL,
  reviewed_by text NOT NULL,
  updated_at timestamp with time zone,
  generated_by uuid,
  CONSTRAINT rm_test_reports_pkey PRIMARY KEY (id),
  CONSTRAINT rm_test_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id),
  CONSTRAINT in_coming_report_supplier_name_fkey FOREIGN KEY (supplier_name) REFERENCES public.suppliers(id)
);
CREATE TABLE public.suppliers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL UNIQUE,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);